// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTe0T1Ckq2aPjPHga2loQL1l5C3_sXHxA',
    appId: '1:653589294288:web:8528addbc03fd727fac2d5',
    messagingSenderId: '653589294288',
    projectId: 'notemaker-1d590',
    authDomain: 'notemaker-1d590.firebaseapp.com',
    storageBucket: 'notemaker-1d590.appspot.com',
    measurementId: 'G-DHKCEVQJ2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQgF23G-WxaU_bjtiM-yA-4CPRLu5_T0',
    appId: '1:653589294288:android:2e89d70b380b921dfac2d5',
    messagingSenderId: '653589294288',
    projectId: 'notemaker-1d590',
    storageBucket: 'notemaker-1d590.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC65UzWW0-GMBDUrryqV_I3IuziolHguJU',
    appId: '1:653589294288:ios:f3a792063ddb87fafac2d5',
    messagingSenderId: '653589294288',
    projectId: 'notemaker-1d590',
    storageBucket: 'notemaker-1d590.appspot.com',
    iosBundleId: 'com.example.sample',
  );
}
